import time
from Arm_Lib import Arm_Device
import socket
import pickle

Arm = Arm_Device()
time.sleep(.1)


# enable=1: clamp,=0: release
def arm_clamp_block(enable):
    if enable == 0:
        Arm.Arm_serial_servo_write(6, 60, 400)
    else:
        Arm.Arm_serial_servo_write(6, 142, 400)
    time.sleep(.5)


# Define control DOFBOT function, control No.1-No.5 servo，p=[S1,S2,S3,S4,S5]
def arm_move(p, s_time=500):
    for i in range(5):
        id = i + 1
        if id == 5:
            time.sleep(.1)
            Arm.Arm_serial_servo_write(id, p[i], int(s_time * 1.2))
        else:
            Arm.Arm_serial_servo_write(id, p[i], s_time)
        time.sleep(.01)
    time.sleep(s_time / 1000)


# DOFBOT moves up
def arm_move_up():
    Arm.Arm_serial_servo_write(2, 90, 1500)
    Arm.Arm_serial_servo_write(3, 90, 1500)
    Arm.Arm_serial_servo_write(4, 90, 1500)
    time.sleep(.1)


# Define variable parameters at different locations


p_top = [90, 130, 0, 0, 270]  # basic position
p_init = [0, 45, 40, 35, 270]  # init_position
p_init2 = [0, 90, 40, 35, 270]
p_ship = [180, 45, 40, 35, 270]
p_ship2 = [180, 90, 40, 35, 270]  # shipping
p_dis = [155, 45, 40, 40, 270]
p_dis2 = [155, 90, 40, 40, 270]  # disposing

# matrix section(3x4)
p_00 = [44, 57, 37, 1, 270]
p_01 = [72, 72, 16, 0, 270]
p_02 = [106, 74, 10, 12, 270]
p_03 = [134, 69, 12, 25, 270]

p_10 = [60, 38, 57, 16, 270]
p_11 = [78, 49, 39, 23, 270]
p_12 = [100, 58, 24, 32, 270]
p_13 = [120, 54, 32, 35, 270]

p_20 = [65, 22, 65, 50, 270]  # A little bit bad position
p_21 = [82, 26, 60, 50, 270]
p_22 = [97, 30, 60, 43, 270]
p_23 = [112, 22, 68, 47, 270]

# 로봇팔 코딩
arm_move(p_top, 1000)

# 수신측 포트 번호
receiver_port = 50000

# 수신자 소켓 생성
receiver_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

# 수신자 소켓을 로컬 IP 주소와 포트 번호에 바인딩
receiver_socket.bind(('', 10000))

# 수신 대기
receiver_socket.listen()

print("수신 대기 중...")

while True:
    # 클라이언트 연결 수락
    client_socket, client_address = receiver_socket.accept()

    print("클라이언트가 연결되었습니다:", client_address)

    # 데이터 수신
    data = b''
    while True:
        chunk = client_socket.recv(4096)
        if not chunk:
            break
        data += chunk
    # 수신된 데이터 역직렬화
    received_list = pickle.loads(data)
    if received_list[0] == "milk":
        if received_list[1] == 0:
            if received_list[2] == 1:
                arm_clamp_block(0)
                arm_move(p_init2, 1000)
                arm_move(p_init, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_00, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
            elif received_list[2] == 2:
                # 첫번쨰 옆으로 옮기고 00좌표로
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_00, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_01, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_init2, 1000)
                arm_move(p_init, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_00, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)

            elif received_list[2] == 3:
                # 2개 옮기고 00좌표로
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_01, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_02, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_00, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_01, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_init2, 1000)
                arm_move(p_init, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_00, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)

            else:
                # 3개 옮기고 00좌표로
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_02, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_03, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_01, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_02, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_00, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_01, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_init2, 1000)
                arm_move(p_init, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_00, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)

        elif received_list[1] == 1:
            if received_list[2] == 2:
                # 그냥 바로 2번쨰로
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_init2, 1000)
                arm_move(p_init, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_01, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)

            elif received_list[2] == 3:
                # 두번쨰꺼 옮기고 2번쨰로
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_01, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_02, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_init2, 1000)
                arm_move(p_init, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_01, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
            else:
                # 2개 옮기고 2번쨰 자리로
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_02, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_03, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_01, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_02, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_init2, 1000)
                arm_move(p_init, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_01, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)

        elif received_list[1] == 2:
            if received_list[2] == 3:
                # 바로 3번쨰로
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_init2, 1000)
                arm_move(p_init, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_02, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
            else:
                # 1개 옮기고 3번쨰로
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_02, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_03, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_init2, 1000)
                arm_move(p_init, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_02, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
        else:
            # received_list[1]==4일떄
            # 바로 4번쨰로 이동
            arm_clamp_block(0)
            arm_move(p_top, 1000)
            arm_move(p_init2, 1000)
            arm_move(p_init, 1000)
            arm_clamp_block(1)
            arm_move(p_top, 1000)
            arm_move(p_03, 1000)
            arm_clamp_block(0)
            arm_move(p_top, 1000)




    elif received_list[0] == 'snack':
        if received_list[1] == 0:
            if received_list[2] == 1:
                # 그냥 00좌표로 이동
                arm_clamp_block(0)
                arm_move(p_init2, 1000)
                arm_move(p_init, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_10, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                print('그냥 00좌표로 이동')
            elif received_list[2] == 2:
                # 첫번쨰 옆으로 옮기고 10좌표로
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_10, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_11, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_init2, 1000)
                arm_move(p_init, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_10, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
            elif received_list[2] == 3:
                # 2개 옮기고 10좌표로
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_11, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_12, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_10, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_11, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_init2, 1000)
                arm_move(p_init, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_10, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
            else:
                # 3개 옮기고 10좌표로
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_12, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_13, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_11, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_12, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_10, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_11, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_init2, 1000)
                arm_move(p_init, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_10, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
        elif received_list[1] == 1:
            if received_list[2] == 2:
                # 그냥 바로 2번쨰로
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_init2, 1000)
                arm_move(p_init, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_11, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
            elif received_list[2] == 3:
                # 두번쨰꺼 옮기고 2번쨰로
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_11, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_12, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_init2, 1000)
                arm_move(p_init, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_11, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
            else:
                # 2개 옮기고 2번쨰 자리로
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_12, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_13, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_11, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_12, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_init2, 1000)
                arm_move(p_init, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_11, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
        elif received_list[1] == 2:
            if received_list[2] == 3:
                # 바로 3번쨰로
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_init2, 1000)
                arm_move(p_init, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_12, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
            else:
                # 1개 옮기고 3번쨰로
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_12, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_13, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_init2, 1000)
                arm_move(p_init, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_12, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
        else:
            # received_list[1]==4일떄
            # 바로 4번쨰로 이동
            arm_clamp_block(0)
            arm_move(p_top, 1000)
            arm_move(p_init2, 1000)
            arm_move(p_init, 1000)
            arm_clamp_block(1)
            arm_move(p_top, 1000)
            arm_move(p_13, 1000)
            arm_clamp_block(0)
            arm_move(p_top, 1000)



    elif received_list[0] == 'gum':
        if received_list[1] == 0:
            if received_list[2] == 1:
                arm_clamp_block(0)
                arm_move(p_init2, 1000)
                arm_move(p_init, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_20, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
            elif received_list[2] == 2:
                # 첫번쨰 옆으로 옮기고 20좌표로
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_20, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_21, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_init2, 1000)
                arm_move(p_init, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_20, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
            elif received_list[2] == 3:
                # 2개 옮기고 20좌표로
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_21, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_22, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_20, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_21, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_init2, 1000)
                arm_move(p_init, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_20, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
            else:
                # 3개 옮기고 20좌표로
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_22, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_23, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_21, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_22, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_20, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_21, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_init2, 1000)
                arm_move(p_init, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_20, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
        elif received_list[1] == 1:
            if received_list[2] == 2:
                # 그냥 바로 2번쨰로
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_init2, 1000)
                arm_move(p_init, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_21, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
            elif received_list[2] == 3:
                # 두번쨰꺼 옮기고 2번쨰로
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_21, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_22, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_init2, 1000)
                arm_move(p_init, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_21, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
            else:
                # 2개 옮기고 2번쨰 자리로
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_22, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_23, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_21, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_22, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_init2, 1000)
                arm_move(p_init, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_21, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
        elif received_list[1] == 2:
            if received_list[2] == 3:
                # 바로 3번쨰로
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_init2, 1000)
                arm_move(p_init, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_22, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
            else:
                # 1개 옮기고 3번쨰로
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_22, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_23, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_init2, 1000)
                arm_move(p_init, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_22, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
        else:

            # 바로 4번쨰로 이동
            arm_clamp_block(0)
            arm_move(p_top, 1000)
            arm_move(p_init2, 1000)
            arm_move(p_init, 1000)
            arm_clamp_block(1)
            arm_move(p_top, 1000)
            arm_move(p_23, 1000)
            arm_clamp_block(0)
            arm_move(p_top, 1000)


    elif received_list[0] == -1:  # 제품 출고하는 코드
        if received_list[1] == 'milk':
            if received_list[2] == 0:
                # 첫번쨰꺼 빼기만 하면 됨
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_00, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_ship2, 1000)
                arm_move(p_ship, 1000)
                arm_clamp_block(0)
                arm_move(p_ship2, 1000)
                arm_move(p_top, 1000)
            elif received_list[2] == 1:
                # 뺴고 1개 옮겨야함
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_00, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_ship2, 1000)
                arm_move(p_ship, 1000)
                arm_clamp_block(0)
                arm_move(p_ship2, 1000)
                arm_move(p_top, 1000)
                arm_move(p_01, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_00, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)

            elif received_list[2] == 2:
                # 뺴고 2개 옮겨야함
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_00, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_ship2, 1000)
                arm_move(p_ship, 1000)
                arm_clamp_block(0)
                arm_move(p_ship2, 1000)
                arm_move(p_top, 1000)
                arm_move(p_01, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_00, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_02, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_01, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
            else:
                # 뺴고 3개 옮겨야함
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_00, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_ship2, 1000)
                arm_move(p_ship, 1000)
                arm_clamp_block(0)
                arm_move(p_ship2, 1000)
                arm_move(p_top, 1000)
                arm_move(p_01, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_00, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_02, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_01, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_03, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_02, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)

        elif received_list[1] == 'snack':
            if received_list[2] == 0:
                # 첫번쨰꺼 빼기만 하면 됨
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_10, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_ship2, 1000)
                arm_move(p_ship, 1000)
                arm_clamp_block(0)
                arm_move(p_ship2, 1000)
                arm_move(p_top, 1000)
            elif received_list[2] == 1:
                # 뺴고 1개 옮겨야함
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_10, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_ship2, 1000)
                arm_move(p_ship, 1000)
                arm_clamp_block(0)
                arm_move(p_ship2, 1000)
                arm_move(p_top, 1000)
                arm_move(p_11, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_10, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
            elif received_list[2] == 2:
                # 뺴고 2개 옮겨야함
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_10, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_ship2, 1000)
                arm_move(p_ship, 1000)
                arm_clamp_block(0)
                arm_move(p_ship2, 1000)
                arm_move(p_top, 1000)
                arm_move(p_11, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_10, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_12, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_11, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
            else:
                # 뺴고 3개 옮겨야함
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_10, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_ship2, 1000)
                arm_move(p_ship, 1000)
                arm_clamp_block(0)
                arm_move(p_ship2, 1000)
                arm_move(p_top, 1000)
                arm_move(p_11, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_10, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_12, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_11, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_13, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_12, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)

        elif received_list[1] == 'gum':
            if received_list[2] == 0:
                # 첫번쨰꺼 빼기만 하면 됨
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_20, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_ship2, 1000)
                arm_move(p_ship, 1000)
                arm_clamp_block(0)
                arm_move(p_ship2, 1000)
                arm_move(p_top, 1000)
            elif received_list[2] == 1:
                # 뺴고 1개 옮겨야함
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_20, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_ship2, 1000)
                arm_move(p_ship, 1000)
                arm_clamp_block(0)
                arm_move(p_ship2, 1000)
                arm_move(p_top, 1000)
                arm_move(p_21, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_20, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
            elif received_list[2] == 2:
                # 뺴고 2개 옮겨야함
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_20, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_ship2, 1000)
                arm_move(p_ship, 1000)
                arm_clamp_block(0)
                arm_move(p_ship2, 1000)
                arm_move(p_top, 1000)
                arm_move(p_21, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_20, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_22, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_21, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
            else:
                # 뺴고 3개 옮겨야함
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_20, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_ship2, 1000)
                arm_move(p_ship, 1000)
                arm_clamp_block(0)
                arm_move(p_ship2, 1000)
                arm_move(p_top, 1000)
                arm_move(p_21, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_20, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_22, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_21, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)
                arm_move(p_23, 1000)
                arm_clamp_block(1)
                arm_move(p_top, 1000)
                arm_move(p_22, 1000)
                arm_clamp_block(0)
                arm_move(p_top, 1000)

    elif received_list[0] == -2:  # dispoing

        for i in range(2, 8, 2):
            if received_list[i] != 0:
                if i == 2:
                    if received_list[1] == 1:
                        if received_list[2] == 1:
                            arm_clamp_block(0)
                            arm_move(p_00, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)

                    elif received_list[1] == 2:
                        if received_list[2] == 1:
                            arm_clamp_block(0)
                            arm_move(p_00, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)
                            arm_move(p_01, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_00, 1000)
                            arm_clamp_block(0)
                            arm_move(p_top, 1000)

                        elif received_list[2] == 2:
                            arm_clamp_block(0)
                            arm_move(p_00, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)
                            arm_clamp_block(0)
                            arm_move(p_01, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)

                    elif received_list[1] == 3:
                        if received_list[2] == 1:
                            arm_clamp_block(0)
                            arm_move(p_00, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)
                            arm_move(p_01, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_00, 1000)
                            arm_clamp_block(0)
                            arm_move(p_top, 1000)
                            arm_move(p_02, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_01, 1000)
                            arm_clamp_block(0)
                            arm_move(p_top, 1000)

                        elif received_list[2] == 2:
                            arm_clamp_block(0)
                            arm_move(p_00, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)
                            arm_clamp_block(0)
                            arm_move(p_01, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)
                            arm_move(p_02, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_00, 1000)
                            arm_clamp_block(0)
                            arm_move(p_top, 1000)


                        elif received_list[2] == 3:
                            arm_clamp_block(0)
                            arm_move(p_00, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)
                            arm_clamp_block(0)
                            arm_move(p_01, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)
                            arm_clamp_block(0)
                            arm_move(p_02, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)

                    elif received_list[1] == 4:
                        if received_list[2] == 1:
                            arm_clamp_block(0)
                            arm_move(p_00, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)
                            arm_clamp_block(0)
                            arm_move(p_top, 1000)
                            arm_move(p_01, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_00, 1000)
                            arm_clamp_block(0)
                            arm_move(p_top, 1000)
                            arm_move(p_02, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_01, 1000)
                            arm_clamp_block(0)
                            arm_move(p_top, 1000)
                            arm_move(p_03, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_02, 1000)
                            arm_clamp_block(0)

                        elif received_list[2] == 2:
                            arm_clamp_block(0)
                            arm_move(p_00, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)
                            arm_clamp_block(0)
                            arm_move(p_01, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)
                            arm_move(p_02, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_00, 1000)
                            arm_clamp_block(0)
                            arm_move(p_top, 1000)
                            arm_move(p_03, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_01, 1000)
                            arm_clamp_block(0)
                            arm_move(p_top, 1000)

                        elif received_list[2] == 3:
                            arm_clamp_block(0)
                            arm_move(p_00, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)
                            arm_clamp_block(0)
                            arm_move(p_01, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)
                            arm_clamp_block(0)
                            arm_move(p_02, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)
                            arm_move(p_03, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_00, 1000)
                            arm_clamp_block(0)
                            arm_move(p_top, 1000)

                        elif received_list[2] == 4:
                            arm_clamp_block(0)
                            arm_move(p_00, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)
                            arm_clamp_block(0)
                            arm_move(p_01, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)
                            arm_clamp_block(0)
                            arm_move(p_02, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)
                            arm_clamp_block(0)
                            arm_move(p_03, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)

                if i == 4:
                    if received_list[3] == 1:
                        if received_list[4] == 1:
                            arm_clamp_block(0)
                            arm_move(p_10, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)

                    elif received_list[3] == 2:
                        if received_list[4] == 1:
                            arm_clamp_block(0)
                            arm_move(p_10, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)
                            arm_move(p_11, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_10, 1000)
                            arm_clamp_block(0)
                            arm_move(p_top, 1000)

                        elif received_list[4] == 2:
                            arm_clamp_block(0)
                            arm_move(p_10, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)
                            arm_clamp_block(0)
                            arm_move(p_11, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)

                    elif received_list[3] == 3:
                        if received_list[4] == 1:
                            arm_clamp_block(0)
                            arm_move(p_10, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)
                            arm_move(p_11, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_10, 1000)
                            arm_clamp_block(0)
                            arm_move(p_top, 1000)
                            arm_move(p_12, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_11, 1000)
                            arm_clamp_block(0)
                            arm_move(p_top, 1000)

                        elif received_list[4] == 2:
                            arm_clamp_block(0)
                            arm_move(p_10, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)
                            arm_clamp_block(0)
                            arm_move(p_11, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)
                            arm_move(p_12, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_10, 1000)
                            arm_clamp_block(0)
                            arm_move(p_top, 1000)

                        elif received_list[4] == 3:
                            arm_clamp_block(0)
                            arm_move(p_10, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)
                            arm_clamp_block(0)
                            arm_move(p_11, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)
                            arm_clamp_block(0)
                            arm_move(p_12, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)

                    elif received_list[3] == 4:
                        if received_list[4] == 1:
                            arm_clamp_block(0)
                            arm_move(p_10, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)
                            arm_clamp_block(0)
                            arm_move(p_top, 1000)
                            arm_move(p_11, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_10, 1000)
                            arm_clamp_block(0)
                            arm_move(p_top, 1000)
                            arm_move(p_12, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_11, 1000)
                            arm_clamp_block(0)
                            arm_move(p_top, 1000)
                            arm_move(p_13, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_12, 1000)
                            arm_clamp_block(0)

                        elif received_list[4] == 2:
                            arm_clamp_block(0)
                            arm_move(p_10, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)
                            arm_clamp_block(0)
                            arm_move(p_11, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)
                            arm_move(p_12, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_10, 1000)
                            arm_clamp_block(0)
                            arm_move(p_top, 1000)
                            arm_move(p_13, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_11, 1000)
                            arm_clamp_block(0)
                            arm_move(p_top, 1000)

                        elif received_list[4] == 3:
                            arm_clamp_block(0)
                            arm_move(p_10, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)
                            arm_clamp_block(0)
                            arm_move(p_11, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)
                            arm_clamp_block(0)
                            arm_move(p_12, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)
                            arm_move(p_13, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_10, 1000)
                            arm_clamp_block(0)
                            arm_move(p_top, 1000)

                        elif received_list[4] == 4:
                            arm_clamp_block(0)
                            arm_move(p_10, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)
                            arm_clamp_block(0)
                            arm_move(p_11, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)
                            arm_clamp_block(0)
                            arm_move(p_12, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)
                            arm_clamp_block(0)
                            arm_move(p_13, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)

                if i == 6:
                    if received_list[5] == 1:
                        if received_list[6] == 1:
                            arm_clamp_block(0)
                            arm_move(p_20, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)

                    elif received_list[5] == 2:
                        if received_list[6] == 1:
                            arm_clamp_block(0)
                            arm_move(p_20, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)
                            arm_move(p_21, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_20, 1000)
                            arm_clamp_block(0)
                            arm_move(p_top, 1000)

                        elif received_list[6] == 2:
                            arm_clamp_block(0)
                            arm_move(p_20, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)
                            arm_clamp_block(0)
                            arm_move(p_21, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)

                    elif received_list[5] == 3:
                        if received_list[6] == 1:
                            arm_clamp_block(0)
                            arm_move(p_20, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)
                            arm_move(p_21, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_20, 1000)
                            arm_clamp_block(0)
                            arm_move(p_top, 1000)
                            arm_move(p_22, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_21, 1000)
                            arm_clamp_block(0)
                            arm_move(p_top, 1000)

                        elif received_list[6] == 2:
                            arm_clamp_block(0)
                            arm_move(p_20, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)
                            arm_clamp_block(0)
                            arm_move(p_21, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)
                            arm_move(p_22, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_20, 1000)
                            arm_clamp_block(0)
                            arm_move(p_top, 1000)

                        elif received_list[6] == 3:
                            arm_clamp_block(0)
                            arm_move(p_20, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)
                            arm_clamp_block(0)
                            arm_move(p_21, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)
                            arm_clamp_block(0)
                            arm_move(p_22, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)


                    elif received_list[5] == 4:
                        if received_list[6] == 1:
                            arm_clamp_block(0)
                            arm_move(p_20, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)
                            arm_clamp_block(0)
                            arm_move(p_top, 1000)
                            arm_move(p_21, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_20, 1000)
                            arm_clamp_block(0)
                            arm_move(p_top, 1000)
                            arm_move(p_22, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_21, 1000)
                            arm_clamp_block(0)
                            arm_move(p_top, 1000)
                            arm_move(p_23, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_22, 1000)
                            arm_clamp_block(0)

                        elif received_list[6] == 2:
                            arm_clamp_block(0)
                            arm_move(p_20, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)
                            arm_clamp_block(0)
                            arm_move(p_21, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)
                            arm_move(p_22, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_20, 1000)
                            arm_clamp_block(0)
                            arm_move(p_top, 1000)
                            arm_move(p_23, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_21, 1000)
                            arm_clamp_block(0)
                            arm_move(p_top, 1000)

                        elif received_list[6] == 3:
                            arm_clamp_block(0)
                            arm_move(p_20, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)
                            arm_clamp_block(0)
                            arm_move(p_21, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)
                            arm_clamp_block(0)
                            arm_move(p_22, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)
                            arm_move(p_23, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_20, 1000)
                            arm_clamp_block(0)
                            arm_move(p_top, 1000)

                        elif received_list[6] == 4:
                            arm_clamp_block(0)
                            arm_move(p_20, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)
                            arm_clamp_block(0)
                            arm_move(p_21, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)
                            arm_clamp_block(0)
                            arm_move(p_22, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)
                            arm_clamp_block(0)
                            arm_move(p_23, 1000)
                            arm_clamp_block(1)
                            arm_move(p_top, 1000)
                            arm_move(p_dis2, 1000)
                            arm_move(p_dis, 1000)
                            arm_clamp_block(0)
                            arm_move(p_dis2, 1000)
                            arm_move(p_top, 1000)
            arm_move(p_top, 1000)
    # 수신된 리스트 출력
    print("수신된 리스트:", received_list)

    # 클라이언트 소켓 닫기
    client_socket.close()